### ISSUE TITLE
raise RuntimeError(f"Failed to collect tests from {entry.path}

### ISSUE THREAD

**Issue by niroshaimos** [freakboy3742/pytest-tldr#25]
Hi, I'm having a bit of trouble using the tool.
When I try to run the pytest_web_ui like so: 'python3 -m pytest_web_ui {path_to_my_project_folder}'
I get an error message: Failed to collect tests from {path_to_my_project_folder}/conftest.py
I can't figure out why it's searching in conftest.py for tests.
The project contains 6 tests in a file named test_program not in a class.
I have no idea why this happens.. Any help will be very much appreciated. Thanks in advance.

**Comment by freakboy3742** [comment]
I'm not clear why this report is related to `pytest-tldr`. The best I can guess is that `pytest` works by itself, but the interaction with `pytest_web_ui` breaks?

If that's the case, my guess would be that `pytest_web_ui` is using some internal behavior of `pytest` to determine the list of tests to run, and `pytest-tldr` is altering that list. If `pytest_web_ui` is getting back an "empty list" of tests as a result of the presence of `pytest-tldr`, that could cause `pytest` to move into "run everything", instead of the specific test path provided at the command line.

That said - I'm inclined to mark this as a wontfix. `pytest_web_ui` is one way to improve pytest's UX by providing a rich navigation interface; `pytest-tldr` takes another approach by making the output more terse. The two aren't *fundamentally* incompatible - and if there's a way to make them play nice together, I'm all for that. However, the most immediate fix here is "don't use both plugins at the same time"; and I'm not likely to have the time myself to dig into addressing an incompatibility with a plugin that I don't use myself. However, if anyone wants to try their hand at a fix, I'm open to suggestions.
